save:
  periodinminutes: 30
messages:
  outsideyourplot: '&6You are outside your plot. &fType /warp %s to warp to your plot'
  outsideplot: '&6You can only build inside plots. &fFind an empty plot'
  notyourplot: '&6You can only build on your own plot. &fType /warp %s to warp to your plot'
  notinplots: '&6You can only build inside plots.'
  alreadytaken: '&6This plot is already taken. &fFind another empty plot.'
  rented: '&eYou now own this plot! Good luck! &fYou can warp to your plot using /warp %s'
  mustbeconstruction: '&ePlease place a block to claim this empty plot.'
  count: '&eOccupied %s out of %s plots (%s empty)'
  count_withdummies: '&eOccupied %s out of %s open plots (%s empty, %s closed)'
  display_owned: '&r%s: %s&r (created %s, modified %s, %s changes)'
  display_exists: '&7%s: (empty)'
  display_dummy: '&8%s: (dummy)'
  newrent: '&ePlayer %s has just claimed plot %s'
  release_owned: '&ePlayer %s''s plot %s has just been released'
  release_exists: '&6Cannot release: Plot %s is not owned'
  release_none: '&6Cannot release: No such plot exists'
  reserve_owned: '&6Cannot reserve: Plot %s is already owned by %s'
  reserve_none: '&6Cannot release: No such plot exists'
# whatsmyplot_owned: 'Your plot number is %s. Type /warp %s to warp to your plot'
# whatsmyplot_none: 'You have no plot'
  whoseplotisthis_owned: '&eThis plot %s is owned by %s'
  whoseplotisthis_exists: '&eThis plot %s is empty'
  whoseplotisthis_none: '&6This is not a plot'
  whereisthatplot_exists: '&ePlot %s is located at %s'
  whereisthatplot_none: '&6No such plot exists'
  whichplotistheirs_owned: '&ePlayer %s owns plot %s'
  whichplotistheirs_none: '&ePlayer %s owns no plot'

