name: Submissions
main: com.brohoof.submissions.SubmissionsPlugin
version: $version
author: SweetieBelle
authors: [Aoloebio, Ha3]
depend: [PermissionsEx, WorldEdit]
description: >
             Submissions plugin.
permissions:
    submissions.admin:
        description: Submissions admin
        default: op
commands:
    subm:
        description: Submissions commands
        permission: submissions.admin
        usage: list() listx() getownerof(plot|location) whereisplot(plot) getplotof(player) release(plot) select(plot [minus]) releaseowner(player) selectowner(player) visualize(plot [minus]) manualrent(plot player) createplot(name+selection) reload() addtry(player) gettry(player) expires(player) timeleft(player)
    saveandremove:
        description: Saves and removes the given plot
        permission: submissions.admin
        usage: /<command> cmcToRemove